"""Compare full traceback text between CPython 3.13 and the in-browser runner."""
import json
import subprocess
import sys

CASES = [
    'x = 5\nif x > 3:\n    print(1)\nelse x < 3:\n    print(2)',
    'x = 5\nif x > 3:\n    print(1)\n  print(2)',
    'x = 5\nelif x > 3:\n    print(1)',
    'x = 5\nif x > 3:\n    print(1)\n    else:\n    print(2)',
    'x = 5\nif x > 3\n    print(x)',
    '2nd_place = 5',
    'x = 12abc',
    'x = 05',
    'name = "Ada"\nprint(nmae)',
    'count = 3\nprint(cuont + 1)',
    'print(lenght([1, 2]))',
    'x = math.sqrt(4)',
    'import math\nprint(math.sqroot(4))',
    's = "hi"\nprint(s.uper())',
    'nums = [1, 2]\nnums.apend(3)',
    'd = {}\nd.has_key("a")',
    'class Dog:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return nmae + " says woof"\nprint(Dog("Rex").speak())',
    'class Dog:\n    def __init__(self, name):\n        self.name = name\nd = Dog("Rex")\nprint(d.nme)',
    'class P:\n    def __init__(self):\n        self.x = 1\n    def show(self):\n        return self.y\nP().show()',
    'def total(items):\n    s = 0\n    for it in items:\n        s += it\n    return s\nprint(total([1, "2"]))',
    'def avg(nums):\n    return sum(nums) / len(nums)\nprint(avg([]))',
    'def f(x):\n    return x * 2\nprint(f(1, 2))',
    'def g(a, b):\n    return a\ng(1)',
    'scores = {"a": 1}\nprint(scores["b"] + 1)',
    'word = "cat"\nprint(word[3])',
    'import random\nrandom.choice([])',
    'True = 1',
    'f() = 5',
    '1 = x',
    'x + 1 = 2',
    'x and y = 1',
    'x = 5 = 6',
    'del f()',
    'f(x) += 1',
    'print(1 2)\nx = 1',
    'def f(n):\n    return f(n + 1)\nf(0)',
    'print("start")\nname = "Ada"\nprint(nmae)',
    'def f(x):\n    return x + "a"\n\nprint(f(1))',
    'x = 10\ny = 0\nprint(x / y)',
    'print("Total: " + 7)',
    'total = "5" + 5',
    'nums = [1, 2, 3]\nprint(nums[3])',
    'nums = [1, 2, 3]\nx = nums[5]',
    'd = {"a": 1}\nprint(d["b"])',
    'print(int("abc"))',
    'x = int("abc")',
    'int("abc")',
    'print(len(5))',
    '"abc".foo()',
    's = "hello"\ns[0] = "H"',
    'for x in 5:\n    print(x)',
    'print(undefined_thing + 1)',
    'def a():\n    return b()\ndef b():\n    return 1 / 0\na()',
    'def f(n):\n    if n == 0:\n        return [][1]\n    return f(n - 1)\nf(3)',
    'x = None\nx.append(3)',
    'print(10 // 0)',
    'value = 3\nprint("Score: " + value + " points")',
    'items = [3, 1, 2]\nitems.sort()\nprint(items[len(items)])',
    'print(Hi)',
    'Print("Hello")',
    'print(max([]))',
    'x = [1, 2]\nx.remove(5)',
    'print(float("1.2.3"))',
    'count = 0\ncount += "1"',
    'print((1 + 2) * "a" - 3)',
    'if 5 > "3":\n    pass',
    'print(abs())',
    'def greet(name):\n    print("Hi", name)\ngreet()',
    'def f():\n    return g()\nf()',
    'print({1, 2}[0])',
    'class A:\n    pass\nA().missing',
    'print("a" * "b")',
    'x = 5\ndef f():\n    x = x + 1\n    return x\nf()',
    'print("x" + str(5) + 5)',
    'print(  10 % 0  )',
    'total = 0\nfor n in [1, 2, "3"]:\n    total = total + n\nprint(total)',
    'words = {"a": 1}\nfor w in ["a", "b"]:\n    print(words[w])',
    'grid = [[1, 2], [3, 4]]\nprint(grid[1][2])',
    'print(1)\nprint(2\nprint(3)',
    'if True\n    print(1)',
    'print("hi"',
    'print("hello)',
    'x = 5\n  y = 6',
    'for i in range(3):\nprint(i)',
    'if x = 5:\n    pass',
    'print("a" b)',
    'x = [1, 2',
    'def f(:\n  pass',
    'print(1))',
    'x = 1 +',
    'whille True:\n    pass',
    'x = (1, 2]',
    'return 5',
    'print "hi"',
    'else:\n    pass',
    'for i in range(3)\n    print(i)',
    'x == 5 = y',
    "s = 'it's'",
    'while True\n    pass',
    'x = 5\nif x > 3:\nprint("big")',
    'def f()\n    return 1',
    'print("a", "b"',
    'print(Ready?)',
    'x = 5 $',
    'a = `b`',
    'if x ! y:\n    pass',
    'print("a" "b" 1)\nx = 5 ?',
    'x = ?\ny = "abc',
    'print(?)',
    'x = 1 ? 2',
    'def f(?): pass',
    'Print("Welcome!")\nprint(Ready?)\nprint(\'Let\'s go")\nprint("Score:" 10)',
    'print("Welcome!")\nprint("Ready?")\nprint(\'Let\'s go")\nprint("Score:" 10)',
    'print("Score:" 10)\nprint("x")',
    'print("Hi\')',
    "print('It's sunny')",
    'x = (1,\ny = ?',
    'print(1 2)\nz = 1abc',
    'print(1 2)\n  x = 1\n y = 2',
    'x = $\nprint(f"{1 +}")',
    'if x:\n    a = 1\n  b = 2\nc = "abc',
    'if x:\n    a = 1\n  b = 2',
    'if x y:\n    pass',
    'while x ?\n    pass',
    'for i in range(3):\n    print(i)\n  print(i ?)',
    'x = 1\nif x:\n        a = 1\n    b = 2\nprint(x',
    'print("hi")\n    print("there")\nprint("x" 1)',
    'name = "Ada"\nprint(f"{name!}")',
    'print(1 2)\ns = "abc',
    'def f():\n    return 1\n   x = 2',
    'print(f"{1 +}")',
    'print(f"{}")',
    'print(f"{name!x}")',
    'print(f"{name")',
    'print(f"a}b")',
    'def f() x:\n    pass',
    'try x:\n    pass',
    'class A x:\n    pass',
    'for i in x y:\n    pass',
    'if x:\n    pass\nelse x:\n    pass',
    'if x:\n    pass\nelif y z:\n    pass',
    'x = 1\nprint(f"{x!r:>5}")\nprint(f"{!r}")',
    'print(f"{x y}")',
    'x = $\ny = f"{"',
    'def f()\n    pass',
    'try\n    pass\nexcept:\n    pass',
    'class A\n    pass',
    'print(f"abc)',
    'x = $\ny = f"abc',
    'x = $\ny = f"a}b"',
    'x = $\ny = f"{1 +}"',
    'y = f"{1 +}"\nz = "abc',
    'name = "Ada"\nprint(f"Hi {nme}")',
    'print(f"{1/0}")',
    'x = [1]\nprint(f"{x[5]}")',
    'print(f"{len(5)}")',
    "d = {}\nprint(f'total: {d[\"a\"]}')",
    'score = 7\nprint(f"Score: {score + \'1\'}")',
    'items = [1, 2]\nprint(f"{items[2]} and {items[0]}")',
    'd = {"a": 1}\nprint(f"{d["a"]}")',
    'x = 5\nprint(f"{x:>{x}}|")',
    'x = 3.14159\nprint(f"{x:\'^10.2f}")',
    'print(f"{1 +\n 2}")',
    'print(f"{"a" + "b"}")',
    'print(f"{f"{1}"}")',
    'names = ["a", "b"]\nprint(f"{", ".join(names)}")',
    'print(f"{"}")',
    'print(f"{1}}")',
    'print(f\'{"}"}\')',
    'print(f"{3!r:>4}|")',
    'x = 7\nprint(f"{x = }")',
    'print(f"{ {"a": 1}["a"] }")',
    'print("Apples")\nprint("Pears")\nprint("Total: " + 10)',
    'print("Countdown")\nprnt(3)\nprint(2)\nprint(1\nprint("Liftoff!")',
    'print("Receipt")\nprint("Bread:" 2)\nprint("Milk: " + 1)\nprint("Each pays:", 3 / 0)',
    'print("Receipt")\nprint("Bread:", 2)\nprint("Milk: " + 1)\nprint("Each pays:", 3 / 0)',
    'print("Receipt")\nprint("Bread:", 2)\nprint("Milk:", 1)\nprint("Each pays:", 3 / 0)',
    'print("Guests:", 12)\nprint("Pizzas:", 3))\nprint("Slices each:", 24 / 0)\nprint("Enjoy the party!)',
    'print("Guests:", 12)\nprint("Pizzas:", 3)\nprint("Slices each:", 24 / 0)\nprint("Enjoy the party!)',
    'prnt("Shop")\nprint("Open")\nprint("Price: " + 4)\nprint("Bye"',
    "print('It's raining')",
    'print("Good morning)\nprint("Have a nice day!")',
    'print("Apples: " + 5)\nprint("Pears: " + 3)\nprint("Total: " + 5 + 3)',
    'print("Welcome")\nprint("Your score:", 10)\nprint("Well done!"',
    'print("Start")\nprint("A" + "B")\nprint("C", 1 + 1)\nprint("D" + 1)\nprint("End")',
    'print("Start")\n  print("End")',
    'Print("Welcome!")\nprint("Ready?")\nprint("Let\'s go")\nprint("Score:", 10)',
]


def main():
    sys.path.insert(0, "tools")
    jobs = [{"kind": "run", "src": c} for c in CASES]
    cp = json.loads(subprocess.run([sys.executable, "tools/cpy_runner.py"], input=json.dumps(jobs), capture_output=True, text=True).stdout)
    script = r'''
const P = require('./dist/pyrun.js');
let input=''; process.stdin.on('data', d => input += d); process.stdin.on('end', () => {
  const out = JSON.parse(input).map((src) => { const r = P.run(src, {filename: 'main.py'}); return r.error ? r.error.traceback : null; });
  process.stdout.write(JSON.stringify(out)); });'''
    pr = json.loads(subprocess.run(["node", "-e", script], input=json.dumps(CASES), capture_output=True, text=True).stdout)
    bad = 0
    for src, c, p in zip(CASES, cp, pr):
        ct = c.get("traceback")
        if ct != p:
            bad += 1
            print("=" * 60)
            print(src)
            print("--- cpython\n" + str(ct))
            print("--- runner\n" + str(p))
    print(f"{len(CASES) - bad}/{len(CASES)} tracebacks identical")


if __name__ == "__main__":
    main()
